apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-manager-sync
subjects:
- kind: ServiceAccount
  name: {{ include "cert-manager-sync.serviceAccountName" . }}
roleRef:
  kind: Role
  name: cert-manager-sync
  apiGroup: rbac.authorization.k8s.io
