apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cert-manager-sync
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
  