apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations: {}
  labels: {}
  name: alertmanager.sre1.dev.bluescape.io
  namespace: ambassador
spec:
  dnsNames:
    - alertmanager.sre1.dev.bluescape.io
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod-dns
  secretName: alertmanager.sre1.dev.bluescape.io
  secretTemplate:
    annotations:
      cert-manager-sync.lestak.sh/sync-enabled: "true" # enable sync on tls secret
      cert-manager-sync.lestak.sh/acm-enabled: "true" # sync certificate to ACM
      cert-manager-sync.lestak.sh/acm-certificate-arn: "" # will be auto-filled by operator for in-place renewals
      cert-manager-sync.lestak.sh/incapsula-site-id: "12345" # incapsula site to attach cert
      cert-manager-sync.lestak.sh/incapsula-secret-name: "cert-manager-sync-poc" # secret in same namespace which contains incapsula api key

