{{- if and .Values.metrics .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cert-manager-sync.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cert-manager-sync.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "cert-manager-sync.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.metrics.port | default 9090 }}
      targetPort: metrics
      protocol: TCP
{{- end }}
